### ISSUE TITLE
Fix Help Command In Bro Client

### ISSUE THREAD

**Issue by threeal** [threeal/threeal-bot#39]
Currently bro client does not show any command when running `bro --help`.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/10202888/215667048-c95aba01-ac90-4765-95b1-7450617911dc.png">

It's possibly happen because we use [flag package](https://pkg.go.dev/flag) but doesn't specify flag like what it normally should do.
Maybe using other package could fix this too?

**Comment by LordRonz** [comment]
we should use [cobra](https://github.com/spf13/cobra)

**Comment by threeal** [comment]
Good idea, let's try that
